// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzP10O7Em8dKXUS40nVGqX9va-XkMjW0',
    appId: '1:753167810629:web:f1825c132621c94cf4a32c',
    messagingSenderId: '753167810629',
    projectId: 'shortflix-notification-service',
    authDomain: 'shortflix-notification-service.firebaseapp.com',
    storageBucket: 'shortflix-notification-service.firebasestorage.app',
    measurementId: 'G-9SLEVC1M68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-Kmq8-PsJh1bDbyBI-DSl5ifMJP_i0M',
    appId: '1:753167810629:android:f8532ade7f36c868f4a32c',
    messagingSenderId: '753167810629',
    projectId: 'shortflix-notification-service',
    storageBucket: 'shortflix-notification-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRRJjttGeqWV6VPFavjnY8MstX85Hdrc',
    appId: '1:753167810629:ios:97752d652169a5f2f4a32c',
    messagingSenderId: '753167810629',
    projectId: 'shortflix-notification-service',
    storageBucket: 'shortflix-notification-service.firebasestorage.app',
    iosBundleId: 'com.mpmg.shortflix',
  );
}
